# Generated by Django 5.2.14 on 2026-05-15 11:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('date_ouverture', models.DateField()),
                ('taux_interet_applique', models.DecimalField(decimal_places=4, default=0, help_text='Annual rate, e.g. 0.0350 for 3.5%.', max_digits=5)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='savings_account', to='members.member')),
            ],
            options={
                'verbose_name': "Compte d'épargne",
                'verbose_name_plural': "Comptes d'épargne",
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_op', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('interet', 'Intérêt')], db_index=True, max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('solde_apres', models.DecimalField(decimal_places=2, help_text='Snapshot of account balance immediately after this row.', max_digits=14)),
                ('date', models.DateTimeField(db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='savings.savingsaccount')),
                ('payment', models.ForeignKey(blank=True, help_text='Backing Payment for deposit/withdrawal; null for system-credited interest.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='savings_transactions', to='payments.payment')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['account', '-date'], name='savings_sav_account_c67eb9_idx')],
            },
        ),
    ]
