# Generated by Django 5.2.14 on 2026-05-23 06:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_membershiprequest_date_entretien_and_more"),
        ("payments", "0003_alter_payment_type"),
        ("savings", "0002_withdrawalrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassicSavingsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actif",
                    models.BooleanField(
                        default=True, help_text="Produit ouvert aux dépôts."
                    ),
                ),
                (
                    "libelle",
                    models.CharField(default="Épargne classique", max_length=120),
                ),
                (
                    "taux_interet_mensuel",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Ratio mensuel (ex. 0.0100 = 1 %). 0 = pas d'intérêt (règles à définir).",
                        max_digits=6,
                    ),
                ),
                (
                    "depot_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Montant minimum par dépôt.",
                        max_digits=14,
                    ),
                ),
                (
                    "depot_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Plafond par dépôt (vide = aucun plafond).",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "retrait_validation_requise",
                    models.BooleanField(
                        default=True,
                        help_text="Retrait soumis à validation de l'administration.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration épargne classique",
                "verbose_name_plural": "Configuration épargne classique",
            },
        ),
        migrations.CreateModel(
            name="ClassicSavingsAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "solde",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("date_ouverture", models.DateField()),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classic_savings_account",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte épargne classique",
                "verbose_name_plural": "Comptes épargne classique",
            },
        ),
        migrations.CreateModel(
            name="ClassicSavingsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_op",
                    models.CharField(
                        choices=[
                            ("depot", "Dépôt"),
                            ("retrait", "Retrait"),
                            ("interet", "Intérêt"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "solde_apres",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Solde du compte juste après cette opération.",
                        max_digits=14,
                    ),
                ),
                ("date", models.DateTimeField(db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="savings.classicsavingsaccount",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Paiement à l'origine du dépôt ; null pour un intérêt système.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classic_savings_transactions",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["account", "-date"],
                        name="savings_cla_account_743dd0_idx",
                    )
                ],
            },
        ),
    ]
