# Generated by Django 5.2.14 on 2026-05-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0003_classicsavingsconfig_classicsavingsaccount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classicsavingstransaction",
            name="type_op",
            field=models.CharField(
                choices=[
                    ("depot", "Dépôt"),
                    ("retrait", "Retrait"),
                    ("interet", "Intérêt"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="savingstransaction",
            name="type_op",
            field=models.CharField(
                choices=[
                    ("depot", "Dépôt"),
                    ("retrait", "Retrait"),
                    ("interet", "Intérêt"),
                    ("retrait_force", "Prélèvement forcé (crédit en contentieux)"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
