# Generated by Django 5.2.14 on 2026-05-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0004_alter_classicsavingstransaction_type_op_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savingsaccount",
            options={
                "verbose_name": "Compte de collecte journalière",
                "verbose_name_plural": "Comptes de collecte journalière",
            },
        ),
        migrations.AddField(
            model_name="classicsavingsaccount",
            name="cycle_courant",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Numéro du cycle annuel en cours. Incrémenté à chaque renouvellement (restitution + frais payés).",
            ),
        ),
        migrations.AddField(
            model_name="classicsavingsaccount",
            name="date_prochaine_maturite",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date à laquelle le contrat 12 mois échoit (restitution + frais ré-inscription). Posée à l'ouverture du compte ou au renouvellement.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="classicsavingsaccount",
            name="statut_renouvellement",
            field=models.CharField(
                choices=[
                    ("actif", "Actif (loin de l'échéance)"),
                    ("notifie", "Rappel d'anniversaire envoyé"),
                    ("urgence", "Échéance imminente"),
                    (
                        "en_attente_paiement",
                        "Maturité atteinte, en attente du paiement de re-inscription",
                    ),
                    ("archive", "Archivé (grace dépassée sans renouvellement)"),
                ],
                db_index=True,
                default="actif",
                help_text="État du cycle de renouvellement annuel.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="savingsaccount",
            name="end_of_month_preference",
            field=models.CharField(
                choices=[
                    ("cash", "Retrait en cash"),
                    ("epargne", "Bascule vers épargne classique"),
                ],
                default="cash",
                help_text="Choix du membre en fin de mois : récupérer en cash le solde (après commission 1%) ou le faire basculer vers l'épargne classique.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="savingstransaction",
            name="nb_jours_couverts",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Nombre de jours couverts par ce versement (multi-jours pré-payé). Défaut 1 = versement journalier classique.",
            ),
        ),
        migrations.AlterField(
            model_name="classicsavingstransaction",
            name="type_op",
            field=models.CharField(
                choices=[
                    ("depot", "Dépôt"),
                    ("retrait", "Retrait"),
                    ("interet", "Intérêt"),
                    (
                        "restitution_maturite",
                        "Restitution intégrale à la maturité 12 mois (refonte 2026)",
                    ),
                    (
                        "frais_renouvellement",
                        "Frais de ré-inscription annuel (refonte 2026)",
                    ),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="savingsaccount",
            name="taux_interet_applique",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="LEGACY 2025 — annual rate. Ignoré en 2026 (collecte = commission).",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="savingstransaction",
            name="type_op",
            field=models.CharField(
                choices=[
                    ("depot", "Dépôt"),
                    ("retrait", "Retrait"),
                    ("interet", "Intérêt"),
                    ("retrait_force", "Prélèvement forcé (crédit en contentieux)"),
                    ("commission", "Commission mensuelle 1% (refonte 2026)"),
                    (
                        "restitution_cash",
                        "Restitution en cash fin de mois (refonte 2026)",
                    ),
                    (
                        "bascule_epargne",
                        "Bascule vers épargne classique fin de mois (refonte 2026)",
                    ),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
