# Generated by Django 5.2.14 on 2026-05-31 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0012_lenderallocation"),
        ("members", "0008_brc_and_seniority"),
        ("savings", "0006_backfill_lot2_maturity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LenderConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="Mode A : True = tout le solde épargne classique est prêtable. False = mode B (tranches explicites uniquement).",
                    ),
                ),
                (
                    "convention_signed_at",
                    models.DateTimeField(
                        help_text="Date de signature de la convention prêteur."
                    ),
                ),
                (
                    "convention_document",
                    models.FileField(
                        blank=True,
                        help_text="Scan PDF / image de la convention signée.",
                        null=True,
                        upload_to="coop/conventions_preteur/%Y/%m/",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de révocation du consentement. Tant qu'il est nul, le membre est considéré comme prêteur actif. Révocation impossible si une tranche est encore engagée dans un crédit.",
                        null=True,
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lender_consent",
                        to="members.member",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lender_consents_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Convention prêteur",
                "verbose_name_plural": "Conventions prêteur",
                "indexes": [
                    models.Index(
                        fields=["revoked_at"], name="savings_len_revoked_8ce242_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LenderTranche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant alloué à cette tranche, en XAF.",
                        max_digits=14,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible (libre d'engagement)"),
                            ("engagee", "Engagée dans un crédit"),
                            ("liberee", "Libérée (crédit clôturé)"),
                            ("annulee", "Annulée par le membre"),
                        ],
                        db_index=True,
                        default="disponible",
                        max_length=12,
                    ),
                ),
                (
                    "engaged_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Horodatage du passage DISPONIBLE → ENGAGEE.",
                        null=True,
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Horodatage du passage ENGAGEE → LIBEREE (crédit clôturé).",
                        null=True,
                    ),
                ),
                (
                    "engaged_in_loan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Crédit qui consomme cette tranche (posé au passage ENGAGEE).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engaged_tranches",
                        to="loans.loan",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lender_tranches",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tranche prêteur",
                "verbose_name_plural": "Tranches prêteur",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "statut"],
                        name="savings_len_member__6978f1_idx",
                    ),
                    models.Index(
                        fields=["statut", "-created_at"],
                        name="savings_len_statut_8512ce_idx",
                    ),
                ],
            },
        ),
    ]
