# Generated by Django 5.2.14 on 2026-06-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0007_lenderconsent_lendertranche"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classicsavingstransaction",
            name="type_op",
            field=models.CharField(
                choices=[
                    ("depot", "Dépôt"),
                    ("retrait", "Retrait"),
                    ("interet", "Intérêt"),
                    (
                        "restitution_maturite",
                        "Restitution intégrale à la maturité 12 mois (refonte 2026)",
                    ),
                    (
                        "frais_renouvellement",
                        "Frais de ré-inscription annuel (refonte 2026)",
                    ),
                    (
                        "interet_preteur",
                        "Part d'intérêts crédit reversée au prêteur (refonte 2026)",
                    ),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
