# Generated by Django 5.2.14 on 2026-06-03 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_nb_jours_couverts"),
        ("savings", "0009_alter_classicsavingstransaction_type_op"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="handed_over_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="handed_over_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="withdrawal_handovers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="mode_paiement",
            field=models.CharField(
                choices=[
                    ("momo", "Mobile Money (payout Tara)"),
                    ("presentiel", "Espèces à l'agence"),
                ],
                default="presentiel",
                help_text="Canal choisi par le membre pour récupérer son argent.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="network",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MTN", "MTN Mobile Money"),
                    ("ORANGE", "Orange Money"),
                    ("WAVE", "Wave"),
                    ("AIRTEL", "Airtel Money"),
                ],
                help_text="Réseau Mobile Money (mode MOMO uniquement).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="payout_payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="withdrawal_request",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="recipient_phone",
            field=models.CharField(
                blank=True,
                help_text="Numéro MOMO/OM où envoyer l'argent (mode MOMO uniquement).",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("approuvee", "Approuvée — remise espèces en attente"),
                    ("en_payout", "Payout Mobile Money en cours"),
                    ("completee", "Complétée (argent remis)"),
                    ("payout_failed", "Payout Mobile Money échoué"),
                    ("rejetee", "Rejetée"),
                ],
                db_index=True,
                default="en_attente",
                max_length=16,
            ),
        ),
    ]
