# Generated by Django 5.2.14 on 2026-06-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0010_withdrawalrequest_handed_over_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classicsavingstransaction",
            name="is_placement",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Sous-canal placement (DEPOT) : True = bloqué jusqu'à `placement_unlock_date`, restitué + intérêt à maturité. Pour les autres TypeOp ce champ reste False.",
            ),
        ),
        migrations.AddField(
            model_name="classicsavingstransaction",
            name="placement_unlock_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date à partir de laquelle le placement devient libre. Posée par le hook au dépôt (date_depot + epargne.placement.lock_months). Null pour tout ce qui n'est pas un DEPOT placement.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="classicsavingstransaction",
            name="type_op",
            field=models.CharField(
                choices=[
                    ("depot", "Dépôt"),
                    ("retrait", "Retrait"),
                    ("interet", "Intérêt"),
                    (
                        "restitution_maturite",
                        "Restitution intégrale à la maturité 12 mois (refonte 2026)",
                    ),
                    (
                        "frais_renouvellement",
                        "Frais de ré-inscription annuel (refonte 2026)",
                    ),
                    (
                        "interet_preteur",
                        "Part d'intérêts crédit reversée au prêteur (refonte 2026)",
                    ),
                    (
                        "retrait_force",
                        "Prélèvement forcé sur épargne classique (crédit contentieux)",
                    ),
                    (
                        "interet_placement",
                        "Intérêt capitalisé à la maturité d'un dépôt placement (refonte 2026)",
                    ),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
