# Generated by Django 5.2.15 on 2026-07-03 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0011_ch3_placement_sous_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='classic_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='savings.classicsavingsaccount'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='classic_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='savings.classicsavingstransaction'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='source',
            field=models.CharField(choices=[('collecte', 'Collecte journalière'), ('classique_libre', 'Épargne classique (part libre)')], db_index=True, default='collecte', help_text="Produit d'épargne d'où provient le retrait.", max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='savings.savingsaccount'),
        ),
    ]
