# Generated by Django 5.2.14 on 2026-07-08 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0015_bookletorder_annee"),
        ("savings", "0012_withdrawalrequest_classic_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classicsavingstransaction",
            name="booklet_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Carnet le plus récent auquel cette écriture est rattachée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classic_savings_transactions",
                to="members.bookletorder",
            ),
        ),
        migrations.AddField(
            model_name="savingstransaction",
            name="booklet_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Carnet le plus récent auquel cette écriture est rattachée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collecte_transactions",
                to="members.bookletorder",
            ),
        ),
    ]
