# Generated by Django 5.2.14 on 2026-07-16 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0033_loanrequest_date_limite_etude"),
        ("savings", "0013_classicsavingstransaction_booklet_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lendertranche",
            name="gele_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Horodatage du passage DISPONIBLE → GELEE.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lendertranche",
            name="gele_par_loan_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Demande de crédit dont la garantie immobilise cette tranche (posé au passage DISPONIBLE → GELEE).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tranches_gelees",
                to="loans.loanrequest",
            ),
        ),
        migrations.AlterField(
            model_name="lendertranche",
            name="statut",
            field=models.CharField(
                choices=[
                    ("disponible", "Disponible (libre d'engagement)"),
                    ("gelee", "Gelée en garantie d'un crédit"),
                    ("engagee", "Engagée dans un crédit"),
                    ("liberee", "Libérée (crédit clôturé)"),
                    ("annulee", "Annulée par le membre"),
                ],
                db_index=True,
                default="disponible",
                max_length=12,
            ),
        ),
    ]
