# Generated by Django 5.2.14 on 2026-07-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0016_alter_classicsavingstransaction_type_op"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingsaccount",
            name="payout_network",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Réseau Mobile Money de destination (MTN, ORANGE…).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="savingsaccount",
            name="payout_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Numéro Mobile Money de destination (préférence mobile_money).",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="savingsaccount",
            name="end_of_month_preference",
            field=models.CharField(
                choices=[
                    ("cash", "Retrait en cash (à l'agence)"),
                    ("mobile_money", "Versement Mobile Money"),
                    ("epargne", "Bascule vers épargne classique"),
                ],
                default="cash",
                help_text="Choix du membre en fin de mois pour le solde restituable (après commission) : récupérer en cash à l'agence, se le faire verser en Mobile Money, ou le basculer vers l'épargne classique.",
                max_length=16,
            ),
        ),
    ]
