# Generated by Django 5.2.14 on 2026-07-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0017_savingsaccount_payout_network_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classicsavingstransaction",
            name="type_op",
            field=models.CharField(
                choices=[
                    ("depot", "Dépôt"),
                    ("retrait", "Retrait"),
                    ("interet", "Intérêt"),
                    (
                        "restitution_maturite",
                        "Restitution intégrale à la maturité 12 mois (refonte 2026)",
                    ),
                    (
                        "frais_renouvellement",
                        "Frais de ré-inscription annuel (refonte 2026)",
                    ),
                    (
                        "interet_preteur",
                        "Part d'intérêts crédit reversée au prêteur (refonte 2026)",
                    ),
                    (
                        "frais_demande_credit",
                        "Frais d'étude crédit prélevés sur l'épargne (2026)",
                    ),
                    (
                        "interets_reconduction",
                        "Intérêts de reconduction prélevés sur l'épargne",
                    ),
                    (
                        "retrait_force",
                        "Prélèvement forcé sur épargne classique (crédit contentieux)",
                    ),
                    (
                        "interet_placement",
                        "Intérêt capitalisé à la maturité d'un dépôt placement (refonte 2026)",
                    ),
                    ("bascule_collecte", "Bascule depuis la collecte (fin de mois)"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
