# Generated by Django 5.2.14 on 2026-08-05 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0019_alter_classicsavingstransaction_type_op"),
    ]

    operations = [
        migrations.AddField(
            model_name="lendertranche",
            name="source_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Dépôt placement à l'origine de la tranche (traçabilité invalidation).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lender_tranches",
                to="savings.classicsavingstransaction",
            ),
        ),
    ]
