# Generated by Django 5.2.17 on 2026-08-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0020_lendertranche_source_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='frais_transaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
