# Generated by Django 5.2.14 on 2026-05-12 12:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        default="GATHE Finance",
                        max_length=255,
                        verbose_name="Raison sociale",
                    ),
                ),
                (
                    "baseline",
                    models.CharField(
                        blank=True,
                        default="Coopérative d'épargne et de crédit au Cameroun",
                        max_length=255,
                        verbose_name="Baseline",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="Rue Mermoz, Akwa, Douala, Cameroun",
                        max_length=255,
                        verbose_name="Adresse du siège",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="+237 6 56 13 06 72",
                        max_length=40,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "landline",
                    models.CharField(
                        blank=True,
                        default="233 42 48 47",
                        max_length=40,
                        verbose_name="Fixe",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="contact@gathe-finance.com",
                        max_length=254,
                        verbose_name="E-mail public",
                    ),
                ),
                (
                    "opening_hours",
                    models.CharField(
                        blank=True,
                        default="Lundi – Vendredi : 8h00 à 17h",
                        max_length=255,
                        verbose_name="Heures d'ouverture (affichage)",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitude (siège)"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitude (siège)"
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True,
                        default="https://www.facebook.com/Gathe237",
                        verbose_name="Facebook",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        default="https://www.linkedin.com/company/gathe237/",
                        verbose_name="LinkedIn",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Numéro WhatsApp (format international, sans +)",
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(
                        blank=True,
                        default="Rejoindre notre coopérative de crédit et d'épargne",
                        max_length=255,
                        verbose_name="Titre du bandeau CTA",
                    ),
                ),
                (
                    "cta_text",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Texte du bandeau CTA"
                    ),
                ),
                (
                    "cta_button_label",
                    models.CharField(
                        blank=True,
                        default="Rejoignez la Coopérative",
                        max_length=80,
                        verbose_name="Libellé du bouton CTA",
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        blank=True,
                        default="GATHE Finance – Coopérative d'épargne et de crédit au Cameroun",
                        max_length=255,
                        verbose_name="Mention de copyright",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coordonnées & contenus globaux",
            },
        ),
        migrations.CreateModel(
            name="SeoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_title",
                    models.CharField(
                        blank=True,
                        default="GATHE Finance — Coopérative d'épargne et de crédit",
                        max_length=255,
                        verbose_name="Titre par défaut",
                    ),
                ),
                (
                    "default_description",
                    models.CharField(
                        blank=True,
                        default="Coopérative d'épargne et de crédit des entrepreneurs camerounais : crédit, épargne, transferts, investissement communautaire et éducation financière.",
                        max_length=300,
                        verbose_name="Description par défaut",
                    ),
                ),
                (
                    "google_site_verification",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Google Search Console (jeton de vérification)",
                    ),
                ),
                (
                    "bing_site_verification",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Bing Webmaster (jeton de vérification)",
                    ),
                ),
                (
                    "plausible_domain",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Domaine Plausible (analytics)",
                    ),
                ),
                (
                    "ga4_measurement_id",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="GA4 Measurement ID (si utilisé)",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Image de partage par défaut (1200×630)",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO & analytics",
            },
        ),
    ]
