# Generated by Django 5.2.14 on 2026-05-15 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cle', models.CharField(db_index=True, max_length=64, unique=True)),
                ('valeur', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
                'ordering': ['cle'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text="e.g. 'loan.approve'", max_length=64)),
                ('entite_type', models.CharField(db_index=True, max_length=64)),
                ('entite_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entite_type', 'entite_id'], name='audit_audit_entite__866049_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx')],
            },
        ),
    ]
