# Generated by Django 5.2.14 on 2026-08-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_blockedip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cooperativeasset",
            name="carnet_specimen",
            field=models.FileField(
                blank=True,
                help_text="PDF spécimen du carnet de cotisations — affiché sur la page Commander carnet (mobile + portail) pour pré-visualisation.",
                null=True,
                upload_to="coop/assets/",
            ),
        ),
        migrations.AlterField(
            model_name="cooperativeasset",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="cooperativeasset",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
