# Generated by Django 5.2.14 on 2026-05-12 12:13

import django.db.models.deletion
import modelsearch.index
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Nom")),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Fonction / rôle"
                    ),
                ),
                (
                    "bio",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Bio courte"),
                ),
                (
                    "link",
                    models.URLField(blank=True, verbose_name="Lien (site, profil…)"),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auteur",
                "verbose_name_plural": "Auteurs",
                "ordering": ["name"],
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nom")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=140, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description courte"
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["name"],
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="KeyFigure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=40, verbose_name="Valeur (ex. 4 500, 400)"
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="Suffixe (ex. « M FCFA », « + »)",
                    ),
                ),
                ("label", models.CharField(max_length=160, verbose_name="Libellé")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordre"),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chiffre clé",
                "verbose_name_plural": "Chiffres clés",
                "ordering": ["sort_order", "id"],
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
