# Generated by Django 5.2.14 on 2026-08-16 06:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0021_member_pieces_a_fournir"),
        ("payments", "0008_alter_payment_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialCollectionMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("caisse_scolaire", "Caisse scolaire"),
                            ("tontine_alimentaire", "Tontine alimentaire"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de validation"),
                            ("valide", "Validé"),
                            ("rejete", "Rejeté"),
                            ("suspendu", "Suspendu"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=16,
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "objectif",
                    models.TextField(
                        help_text="Ce que le membre attend de sa collecte (saisi à la demande)."
                    ),
                ),
                (
                    "montant_cible",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Objectif chiffré facultatif renseigné par le membre.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "form_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Champs additionnels du formulaire (extensible sans migration).",
                    ),
                ),
                ("motif_rejet", models.TextField(blank=True, default="")),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_collections",
                        to="members.member",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_special_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation collecte particulière",
                "verbose_name_plural": "Participations collectes particulières",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SpecialCollectionTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_op",
                    models.CharField(
                        choices=[
                            ("versement", "Versement (Mobile Money)"),
                            ("transfert", "Transfert entrant (épargne classique)"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "solde_apres",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Solde de la collecte juste après cette opération.",
                        max_digits=14,
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Libellé lisible (ex. « Transfert depuis épargne classique »).",
                        max_length=120,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="special_collections.specialcollectionmembership",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Paiement Mobile Money à l'origine ; null pour un transfert interne.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="special_collection_transactions",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture collecte particulière",
                "verbose_name_plural": "Écritures collectes particulières",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="specialcollectionmembership",
            constraint=models.UniqueConstraint(
                fields=("member", "type"), name="uniq_member_special_collection_type"
            ),
        ),
        migrations.AddIndex(
            model_name="specialcollectiontransaction",
            index=models.Index(
                fields=["membership", "-created_at"],
                name="special_col_members_411d9c_idx",
            ),
        ),
    ]
