# Generated by Django 5.2.14 on 2026-08-16 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def create_initial_cycles(apps, schema_editor):
    """Rattache les participations déjà existantes à un « cycle initial » ouvert
    par type (pas de perte lors du passage au modèle par cycles)."""
    Cycle = apps.get_model("special_collections", "SpecialCollectionCycle")
    Membership = apps.get_model("special_collections", "SpecialCollectionMembership")
    today = timezone.now().date()
    types = (
        Membership.objects.filter(cycle__isnull=True)
        .values_list("type", flat=True)
        .distinct()
    )
    for type_ in types:
        cycle, _ = Cycle.objects.get_or_create(
            type=type_,
            statut="ouvert",
            defaults={"nom": "Cycle initial", "date_debut": today},
        )
        Membership.objects.filter(type=type_, cycle__isnull=True).update(cycle=cycle)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0021_member_pieces_a_fournir"),
        ("special_collections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialCollectionCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("caisse_scolaire", "Caisse scolaire"),
                            ("tontine_alimentaire", "Tontine alimentaire"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Libellé du cycle (ex. « Caisse scolaire 2026-2027 »).",
                        max_length=120,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("ouvert", "Ouvert"), ("clos", "Clos")],
                        db_index=True,
                        default="ouvert",
                        max_length=8,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Cycle de collecte particulière",
                "verbose_name_plural": "Cycles de collectes particulières",
                "ordering": ["-date_debut", "-id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="specialcollectionmembership",
            name="uniq_member_special_collection_type",
        ),
        migrations.AddField(
            model_name="specialcollectioncycle",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="special_collection_cycles_closed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="specialcollectioncycle",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="special_collection_cycles_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="specialcollectionmembership",
            name="cycle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="special_collections.specialcollectioncycle",
            ),
        ),
        # Rattache les participations existantes à un cycle initial ouvert.
        migrations.RunPython(create_initial_cycles, _noop),
        # Puis rend le cycle obligatoire (toutes les lignes en ont un désormais).
        migrations.AlterField(
            model_name="specialcollectionmembership",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="special_collections.specialcollectioncycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="specialcollectionmembership",
            constraint=models.UniqueConstraint(
                fields=("member", "cycle"), name="uniq_member_special_collection_cycle"
            ),
        ),
        migrations.AddConstraint(
            model_name="specialcollectioncycle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("statut", "ouvert")),
                fields=("type",),
                name="uniq_open_cycle_per_type",
            ),
        ),
    ]
