# Generated by Django 5.2.14 on 2026-08-27 06:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0022_bookletorder_type"),
        ("special_collections", "0002_specialcollectioncycle_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="specialcollectioncycle",
            name="uniq_open_cycle_per_type",
        ),
        migrations.AddField(
            model_name="specialcollectioncycle",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Informations complémentaires (règles, dates clés, modalités).",
            ),
        ),
        migrations.AddField(
            model_name="specialcollectioncycle",
            name="montant_minimal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Montant minimal par versement (plancher). 0 = pas de plancher.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="specialcollectiontransaction",
            name="booklet_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="special_collection_transactions",
                to="members.bookletorder",
            ),
        ),
        migrations.AddField(
            model_name="specialcollectiontransaction",
            name="date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date effective (antidatable). Null → created_at.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="specialcollectioncycle",
            name="nom",
            field=models.CharField(
                help_text="Titre de la collecte (ex. « Tontine alimentaire fêtes 2026 »).",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="specialcollectiontransaction",
            name="type_op",
            field=models.CharField(
                choices=[
                    ("versement", "Versement (Mobile Money)"),
                    ("transfert", "Transfert entrant (épargne classique)"),
                    ("manuel", "Versement manuel (agence / reprise)"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
