# Generated by Django 5.2.14 on 2026-08-27 08:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0022_bookletorder_type"),
        ("payments", "0010_payment_special_cycle"),
        ("special_collections", "0004_grandfather_participant_carnets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupTontine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de la réunion / du groupe.", max_length=120
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "solde",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "montant_cotisation",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("ouvert", "Ouverte"), ("clos", "Clôturée")],
                        db_index=True,
                        default="ouvert",
                        max_length=8,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_tontines_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_tontines_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tontine de groupe",
                "verbose_name_plural": "Tontines de groupe",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GroupTontineLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                ("solde_restant", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "statut",
                    models.CharField(
                        choices=[("en_cours", "En cours"), ("solde", "Soldé")],
                        db_index=True,
                        default="en_cours",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_tontine_loans_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="special_collections.grouptontine",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_tontine_loans",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prêt de tontine de groupe",
                "verbose_name_plural": "Prêts de tontines de groupe",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GroupTontineMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("president", "Président"),
                            ("tresorier", "Trésorier"),
                            ("membre", "Membre"),
                        ],
                        db_index=True,
                        default="membre",
                        max_length=12,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="special_collections.grouptontine",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_tontine_memberships",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre de tontine de groupe",
                "verbose_name_plural": "Membres de tontines de groupe",
                "ordering": ["role", "member__nom", "member__prenom"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "member"), name="uniq_group_tontine_member"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GroupTontineTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_op",
                    models.CharField(
                        choices=[
                            ("cotisation", "Cotisation (entrée)"),
                            ("versement_beneficiaire", "Versement à un bénéficiaire"),
                            ("pret", "Prêt à un membre (sortie)"),
                            ("remboursement_pret", "Remboursement de prêt (entrée)"),
                            ("ajustement", "Ajustement"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                ("solde_apres", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Date effective (antidatable). Null → created_at.",
                        null=True,
                    ),
                ),
                ("libelle", models.CharField(blank=True, default="", max_length=160)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="special_collections.grouptontine",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="special_collections.grouptontineloan",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Membre concerné (cotisant, bénéficiaire, emprunteur).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_tontine_transactions",
                        to="members.member",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_tontine_transactions",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture de tontine de groupe",
                "verbose_name_plural": "Écritures de tontines de groupe",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["group", "-created_at"],
                        name="special_col_group_i_5931d9_idx",
                    )
                ],
            },
        ),
    ]
