# Generated by Django 5.2.14 on 2026-08-27 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "special_collections",
            "0005_grouptontine_grouptontineloan_grouptontinemember_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptontinetransaction",
            name="acted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_tontine_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
