# Generated by Django 5.2.17 on 2026-08-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_collections', '0006_grouptontinetransaction_acted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcollectioncycle',
            name='nom',
            field=models.CharField(help_text='Titre de la collecte (ex. « Tontine des fêtes 2026 », « Caisse scolaire »).', max_length=120),
        ),
        migrations.AlterField(
            model_name='specialcollectioncycle',
            name='type',
            field=models.CharField(choices=[('caisse_scolaire', 'Caisse scolaire'), ('tontine_alimentaire', 'Tontine')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='specialcollectionmembership',
            name='type',
            field=models.CharField(choices=[('caisse_scolaire', 'Caisse scolaire'), ('tontine_alimentaire', 'Tontine')], db_index=True, max_length=32),
        ),
    ]
