# Generated by Django 5.2.17 on 2026-08-28 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_alter_bookletorder_type'),
        ('special_collections', '0007_alter_specialcollectioncycle_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptontineloan',
            name='avaliste',
            field=models.ForeignKey(blank=True, help_text='Avaliste (informatif) — membre du roster, si applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_tontine_loans_backed', to='members.member'),
        ),
        migrations.AddField(
            model_name='grouptontineloan',
            name='avaliste_nom',
            field=models.CharField(blank=True, default='', help_text='Avaliste (informatif) — nom libre si hors réunion.', max_length=120),
        ),
        migrations.CreateModel(
            name='GroupTontineRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(help_text='Nom du rôle (ex. « Secrétaire »).', max_length=60)),
                ('can_manage_funds', models.BooleanField(default=False, help_text='Verser à un bénéficiaire (payout).')),
                ('can_grant_loan', models.BooleanField(default=False, help_text='Accorder un prêt de la cagnotte.')),
                ('can_manage_roster', models.BooleanField(default=False, help_text='Ajouter/retirer des membres et changer les rôles.')),
                ('can_record_cotisation', models.BooleanField(default=False, help_text='Enregistrer des cotisations.')),
                ('can_close', models.BooleanField(default=False, help_text='Clôturer la réunion.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='special_collections.grouptontine')),
            ],
            options={
                'verbose_name': 'Rôle personnalisé de réunion',
                'verbose_name_plural': 'Rôles personnalisés de réunion',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='grouptontinemember',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='special_collections.grouptontinerole'),
        ),
        migrations.AddConstraint(
            model_name='grouptontinerole',
            constraint=models.UniqueConstraint(fields=('group', 'nom'), name='uniq_group_tontine_role_name'),
        ),
    ]
