# Generated by Django 5.2.17 on 2026-08-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_collections', '0008_grouptontineloan_avaliste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcollectiontransaction',
            name='type_op',
            field=models.CharField(choices=[('versement', 'Versement (Mobile Money)'), ('transfert', 'Transfert entrant (épargne classique)'), ('manuel', 'Versement manuel (agence / reprise)'), ('retrait', 'Retrait / décaissement')], db_index=True, max_length=16),
        ),
    ]
