# Generated by Django 5.2.14 on 2026-09-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "special_collections",
            "0010_specialcollectiontransaction_is_antidated_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouptontinerole",
            name="can_manage_roster",
            field=models.BooleanField(
                default=False,
                help_text="DÉPRÉCIÉ — sans effet. Réservé à l'administrateur.",
            ),
        ),
    ]
