# Generated by Django 5.2.14 on 2026-09-19 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("special_collections", "0011_alter_grouptontinerole_can_manage_roster"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptontinetransaction",
            name="corrected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouptontinetransaction",
            name="corrected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grouptontinetransaction",
            name="correction_note",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="grouptontinetransaction",
            name="destination",
            field=models.CharField(
                blank=True,
                choices=[
                    ("epargne", "Crédité sur l'épargne classique"),
                    ("cash", "Remis en espèces"),
                ],
                default="",
                max_length=12,
            ),
        ),
    ]
