# Generated by Django 5.2.14 on 2026-08-27 11:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0022_bookletorder_type"),
        ("payments", "0011_payment_group_tontine_alter_payment_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "solde",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("active", "Active"), ("cloturee", "Clôturée")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="structures_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Structure (employeur)",
                "verbose_name_plural": "Structures (employeurs)",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "periode",
                    models.CharField(
                        help_text="Libellé de période (ex. « Août 2026 »).",
                        max_length=60,
                    ),
                ),
                (
                    "total_verse",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("employes_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_runs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_runs",
                        to="structures.structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot de paie",
                "verbose_name_plural": "Lots de paie",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StructureEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("poste", models.CharField(blank=True, default="", max_length=120)),
                ("attribution", models.TextField(blank=True, default="")),
                (
                    "montant_paie",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="structure_employments",
                        to="members.member",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="structures.structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employé rattaché",
                "verbose_name_plural": "Employés rattachés",
                "ordering": ["member__nom", "member__prenom"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("structure", "member"), name="uniq_structure_member"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StructureTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_op",
                    models.CharField(
                        choices=[
                            ("approvisionnement", "Approvisionnement (entrée)"),
                            ("versement_paie", "Versement de paie (sortie)"),
                            ("retrait_fonds", "Retrait de fonds (sortie)"),
                            ("ajustement", "Ajustement"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "solde_apres",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Solde de la cagnotte après l'opération.",
                        max_digits=14,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Date effective (antidatable). Null → created_at.",
                        null=True,
                    ),
                ),
                ("libelle", models.CharField(blank=True, default="", max_length=160)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employé concerné (pour un versement de paie).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="structure_transactions",
                        to="members.member",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="structure_transactions",
                        to="payments.payment",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="structures.payrollrun",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="structures.structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture de structure",
                "verbose_name_plural": "Écritures de structures",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["structure", "-created_at"],
                        name="structures__structu_a06a3d_idx",
                    )
                ],
            },
        ),
    ]
