# Generated by Django 5.2.14 on 2026-05-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "city",
                    models.CharField(blank=True, max_length=160, verbose_name="Ville"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse e-mail"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "language",
                    models.CharField(default="fr", max_length=8, verbose_name="Langue"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reçu le"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=400, verbose_name="Navigateur"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notes internes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("in_progress", "En traitement"),
                            ("done", "Traité"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-submitted_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MembershipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "city",
                    models.CharField(blank=True, max_length=160, verbose_name="Ville"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse e-mail"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "language",
                    models.CharField(default="fr", max_length=8, verbose_name="Langue"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reçu le"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=400, verbose_name="Navigateur"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notes internes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle"),
                            ("contacted", "Contacté"),
                            ("processing", "Dossier en cours"),
                            ("approved", "Validé"),
                            ("rejected", "Refusé"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'adhésion",
                "verbose_name_plural": "Demandes d'adhésion",
                "ordering": ["-submitted_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adresse e-mail"
                    ),
                ),
                (
                    "language",
                    models.CharField(default="fr", max_length=8, verbose_name="Langue"),
                ),
                (
                    "consent",
                    models.BooleanField(default=True, verbose_name="Consentement"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=120, verbose_name="Source"),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Inscrit le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Inscrit newsletter",
                "verbose_name_plural": "Inscrits newsletter",
                "ordering": ["-subscribed_at"],
            },
        ),
    ]
