# Generated by Django 5.2.14 on 2026-05-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipRequest',
        ),
    ]
