# Generated by Django 5.2.14 on 2026-05-12 12:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPostPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date de publication")),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, max_length=400, verbose_name="Extrait"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 4),
                            ("rich_text", 6),
                            ("callout", 9),
                            ("image", 13),
                            ("quote", 17),
                            ("cta_band", 23),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Sur-titre (eyebrow)", "required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "label": "Chapô",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Gauche"),
                                        ("center", "Centré"),
                                    ],
                                    "label": "Alignement",
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 0),
                                        ("title", 1),
                                        ("text", 2),
                                        ("alignment", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document-link",
                                        "hr",
                                        "blockquote",
                                    ],
                                    "label": "Contenu",
                                },
                            ),
                            6: ("wagtail.blocks.StructBlock", [[("body", 5)]], {}),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Information (bleu)"),
                                        ("success", "Positif (vert)"),
                                        ("neutral", "Neutre"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("style", 7), ("title", 8), ("body", 5)]],
                                {},
                            ),
                            10: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Légende", "required": False},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Texte alternatif (si différent du titre)",
                                    "required": False,
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 10), ("caption", 11), ("alt", 12)]],
                                {},
                            ),
                            14: ("wagtail.blocks.TextBlock", (), {"label": "Citation"}),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Auteur", "required": False},
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Rôle / activité", "required": False},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 14), ("author", 15), ("role", 16)]],
                                {},
                            ),
                            18: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "label": "Utiliser le bandeau « Rejoindre la coopérative » global",
                                    "required": False,
                                },
                            ),
                            19: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre (si non global)", "required": False},
                            ),
                            20: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "label": "Texte (si non global)",
                                    "required": False,
                                },
                            ),
                            21: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Libellé du bouton (si non global)",
                                    "required": False,
                                },
                            ),
                            22: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page cible du bouton", "required": False},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("use_site_default", 18),
                                        ("title", 19),
                                        ("text", 20),
                                        ("button_label", 21),
                                        ("button_page", 22),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Contenu de l'article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de blog",
                "ordering": ["-date"],
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(
                        blank=True,
                        default="Coopérative d'épargne et de crédit",
                        max_length=160,
                        verbose_name="Sur-titre du héros",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Un avenir financier entre vos mains",
                        max_length=200,
                        verbose_name="Titre du héros",
                    ),
                ),
                (
                    "hero_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Ex. « Que vous démarriez une activité ou cherchiez à la développer… »",
                        verbose_name="Texte du héros",
                    ),
                ),
                (
                    "hero_primary_label",
                    models.CharField(
                        blank=True,
                        default="Rejoindre la coopérative",
                        max_length=80,
                        verbose_name="Libellé bouton principal",
                    ),
                ),
                (
                    "hero_secondary_label",
                    models.CharField(
                        blank=True,
                        default="Découvrir nos services",
                        max_length=80,
                        verbose_name="Libellé bouton secondaire",
                    ),
                ),
                (
                    "intro_title",
                    models.CharField(
                        blank=True,
                        default="Gathe finance, la coopérative d'épargne et de crédit des entrepreneurs",
                        max_length=200,
                        verbose_name="Titre du bloc présentation",
                    ),
                ),
                (
                    "intro_text",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Texte du bloc présentation"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 4),
                            ("rich_text", 6),
                            ("callout", 9),
                            ("image", 13),
                            ("quote", 17),
                            ("cta_band", 23),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Sur-titre (eyebrow)", "required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "label": "Chapô",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Gauche"),
                                        ("center", "Centré"),
                                    ],
                                    "label": "Alignement",
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 0),
                                        ("title", 1),
                                        ("text", 2),
                                        ("alignment", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document-link",
                                        "hr",
                                        "blockquote",
                                    ],
                                    "label": "Contenu",
                                },
                            ),
                            6: ("wagtail.blocks.StructBlock", [[("body", 5)]], {}),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Information (bleu)"),
                                        ("success", "Positif (vert)"),
                                        ("neutral", "Neutre"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("style", 7), ("title", 8), ("body", 5)]],
                                {},
                            ),
                            10: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Légende", "required": False},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Texte alternatif (si différent du titre)",
                                    "required": False,
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 10), ("caption", 11), ("alt", 12)]],
                                {},
                            ),
                            14: ("wagtail.blocks.TextBlock", (), {"label": "Citation"}),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Auteur", "required": False},
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Rôle / activité", "required": False},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 14), ("author", 15), ("role", 16)]],
                                {},
                            ),
                            18: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "label": "Utiliser le bandeau « Rejoindre la coopérative » global",
                                    "required": False,
                                },
                            ),
                            19: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre (si non global)", "required": False},
                            ),
                            20: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "label": "Texte (si non global)",
                                    "required": False,
                                },
                            ),
                            21: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Libellé du bouton (si non global)",
                                    "required": False,
                                },
                            ),
                            22: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page cible du bouton", "required": False},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("use_site_default", 18),
                                        ("title", 19),
                                        ("text", 20),
                                        ("button_label", 21),
                                        ("button_page", 22),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Sections additionnelles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page d'accueil",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 4),
                            ("rich_text", 6),
                            ("callout", 9),
                            ("image", 13),
                            ("quote", 17),
                            ("cta_band", 23),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Sur-titre (eyebrow)", "required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "label": "Chapô",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Gauche"),
                                        ("center", "Centré"),
                                    ],
                                    "label": "Alignement",
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 0),
                                        ("title", 1),
                                        ("text", 2),
                                        ("alignment", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document-link",
                                        "hr",
                                        "blockquote",
                                    ],
                                    "label": "Contenu",
                                },
                            ),
                            6: ("wagtail.blocks.StructBlock", [[("body", 5)]], {}),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Information (bleu)"),
                                        ("success", "Positif (vert)"),
                                        ("neutral", "Neutre"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("style", 7), ("title", 8), ("body", 5)]],
                                {},
                            ),
                            10: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Légende", "required": False},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Texte alternatif (si différent du titre)",
                                    "required": False,
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 10), ("caption", 11), ("alt", 12)]],
                                {},
                            ),
                            14: ("wagtail.blocks.TextBlock", (), {"label": "Citation"}),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Auteur", "required": False},
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Rôle / activité", "required": False},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 14), ("author", 15), ("role", 16)]],
                                {},
                            ),
                            18: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "label": "Utiliser le bandeau « Rejoindre la coopérative » global",
                                    "required": False,
                                },
                            ),
                            19: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre (si non global)", "required": False},
                            ),
                            20: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "label": "Texte (si non global)",
                                    "required": False,
                                },
                            ),
                            21: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Libellé du bouton (si non global)",
                                    "required": False,
                                },
                            ),
                            22: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page cible du bouton", "required": False},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("use_site_default", 18),
                                        ("title", 19),
                                        ("text", 20),
                                        ("button_label", 21),
                                        ("button_page", 22),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Contenu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page éditoriale / légale",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Introduction"
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Image de partage (Open Graph)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog (liste)",
            },
            bases=("wagtailcore.page",),
        ),
    ]
