# Generated by Django 5.2.15 on 2026-07-16 23:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='body_en',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Contenu (EN)'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=400, verbose_name='Extrait (EN)'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titre (EN)'),
        ),
    ]
