# Generated by Django 5.2.14 on 2026-05-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            (
                                "LOAN_INTEREST",
                                "Taux d'intérêt crédit (par transaction)",
                            ),
                            (
                                "SAVINGS_INTEREST_MONTHLY",
                                "Taux d'intérêt épargne (mensuel)",
                            ),
                            ("RENEWAL_CASH", "Reconduction — intérêts au comptant"),
                            ("RENEWAL_DEFERRED", "Reconduction — intérêts reportés"),
                            ("LATE_PENALTY", "Pénalité de non-versement"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("libelle", models.CharField(max_length=120)),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Ratio entre 0 et 1 (ex. 0.1000 pour 10 %).",
                        max_digits=6,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Taux métier",
                "verbose_name_plural": "Taux métier",
                "ordering": ["code"],
            },
        ),
    ]
