# Generated by Django 5.2.14 on 2026-05-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_rateparam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[
                    ("epargne", "Épargne"),
                    ("epargne_classique", "Épargne classique"),
                    ("frais_inscription", "Frais d'inscription"),
                    ("frais_adhesion", "Frais d'adhésion"),
                    ("frais_demande_credit", "Frais de demande de crédit"),
                    ("frais_reconduction", "Frais de reconduction"),
                    ("frais_carnet", "Frais de carnet"),
                    ("remboursement", "Remboursement"),
                    ("decaissement", "Décaissement"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
