# Generated by Django 5.2.14 on 2026-09-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop_notifications", "0006_notificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="transport",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("primary", "Brevo (nominal)"),
                    ("fallback", "SMTP de secours (spam probable)"),
                ],
                db_index=True,
                default="",
                help_text="Voie d'envoi réelle : Brevo (nominal) ou SMTP de secours.",
                max_length=12,
            ),
        ),
    ]
