# Generated by Django 5.2.14 on 2026-07-08 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contentcomment",
            new_name="social_cont_content_89b527_idx",
            old_name="social_cmt_ct_obj_dt_idx",
        ),
        migrations.RenameIndex(
            model_name="contentcomment",
            new_name="social_cont_hidden_372aab_idx",
            old_name="social_cmt_hidden_dt_idx",
        ),
        migrations.RenameIndex(
            model_name="contentreaction",
            new_name="social_cont_content_828e76_idx",
            old_name="social_react_ct_obj_idx",
        ),
        migrations.AddField(
            model_name="contentcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="social.contentcomment",
            ),
        ),
        migrations.AddIndex(
            model_name="contentcomment",
            index=models.Index(
                fields=["parent", "created_at"], name="social_cont_parent__ee8bcc_idx"
            ),
        ),
    ]
