# Generated by Django 5.2.14 on 2026-06-10 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("adhesion", "Adhésion"),
                            ("loan_request", "Demande de crédit"),
                            ("loan_renewal", "Reconduction crédit"),
                        ],
                        db_index=True,
                        help_text="Type de formulaire métier (un schéma actif par kind à la fois).",
                        max_length=32,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        help_text="Numéro de version. Incrémenté par l'admin à chaque modification."
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titre affiché en tête du formulaire (peut différer de la version par défaut).",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description courte affichée sous le titre côté portail.",
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        default=dict,
                        help_text="Structure JSON du formulaire (sections, champs, conditions).",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Version servie aux utilisateurs. Un seul actif par kind.",
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Horodatage de la dernière activation. Null si jamais activée.",
                        null=True,
                    ),
                ),
                (
                    "notes_admin",
                    models.TextField(
                        blank=True,
                        help_text="Notes internes admin (changelog, raison de la modification).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_schemas_activated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_schemas_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Schéma de formulaire",
                "verbose_name_plural": "Schémas de formulaire",
                "ordering": ["kind", "-version"],
                "indexes": [
                    models.Index(
                        fields=["kind", "is_active"], name="coop_forms__kind_cd35ed_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "version"),
                        name="formschema_unique_kind_version",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("kind",),
                        name="formschema_one_active_per_kind",
                    ),
                ],
            },
        ),
    ]
