# Generated by Django 5.2.14 on 2026-05-15 11:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nouvelle_duree_mois', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('demandee', 'Demandée'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], db_index=True, default='demandee', max_length=12)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reconduction',
                'verbose_name_plural': 'Reconductions',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_impute', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=14)),
                ('duree_mois', models.PositiveIntegerField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_instruction', 'En instruction'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], db_index=True, default='en_attente', max_length=16)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Demande de crédit',
                'verbose_name_plural': 'Demandes de crédit',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_dossier', models.CharField(db_index=True, max_length=32, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('taux_interet', models.DecimalField(decimal_places=4, help_text='Annual rate at contract signing, e.g. 0.1200 for 12%.', max_digits=5)),
                ('duree_mois', models.PositiveIntegerField()),
                ('date_decaissement', models.DateField()),
                ('date_premiere_echeance', models.DateField()),
                ('montant_total_du', models.DecimalField(decimal_places=2, help_text='Principal + total interests over full term.', max_digits=14)),
                ('solde_restant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_retard', 'En retard'), ('cloture', 'Clôturé'), ('contentieux', 'Contentieux')], db_index=True, default='actif', max_length=12)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='members.member')),
            ],
            options={
                'ordering': ['-date_decaissement'],
            },
        ),
        migrations.CreateModel(
            name='LoanGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_garantie', models.CharField(choices=[('caution', 'Caution'), ('bien_immobilier', 'Bien immobilier'), ('vehicule', 'Véhicule'), ('depot_garantie', 'Dépôt de garantie')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('valeur_estimee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='loans.loan')),
            ],
            options={
                'verbose_name': 'Garantie',
                'verbose_name_plural': 'Garanties',
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_echeance', models.PositiveIntegerField()),
                ('date_echeance', models.DateField(db_index=True)),
                ('montant_capital', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_interets', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('payee', 'Payée'), ('en_retard', 'En retard'), ('partielle', 'Partielle')], db_index=True, default='a_venir', max_length=12)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan')),
            ],
            options={
                'ordering': ['loan', 'numero_echeance'],
            },
        ),
    ]
