# Generated by Django 5.2.14 on 2026-05-15 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('members', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrenewal',
            name='frais_reconduction_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_fees', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='loanrenewal',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loaninstallment'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayments', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='instruit_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requests_instructed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to='members.member'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='loans.loanrequest'),
        ),
        migrations.AddConstraint(
            model_name='loaninstallment',
            constraint=models.UniqueConstraint(fields=('loan', 'numero_echeance'), name='loan_installment_unique'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['member', 'statut'], name='loans_loan_member__8897b7_idx'),
        ),
    ]
