# Generated by Django 5.2.14 on 2026-05-15 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
        ('members', '0002_membershiprequest_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='avis_instruction',
            field=models.TextField(blank=True, help_text="Recommandation rédigée par l'agent staff après examen du dossier."),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='date_comite',
            field=models.DateTimeField(blank=True, help_text='Date effective de la délibération du comité (≠ date de saisie).', null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='decide_par',
            field=models.ForeignKey(blank=True, help_text='Président du comité qui a enregistré la décision dans le système.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requests_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='duree_revisee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='montant_revise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='pv_comite',
            field=models.ForeignKey(blank=True, help_text='PV signé de la délibération comité, uploadé par le président.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requests_pv', to='members.document'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='scoring',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Score 0-10 attribué par l'agent à l'issue de l'instruction.", null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente (frais à payer)'), ('en_instruction', 'En instruction'), ('en_attente_acceptation_membre', 'Contre-proposition à accepter'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], db_index=True, default='en_attente', max_length=32),
        ),
    ]
