# Generated by Django 5.2.14 on 2026-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanrequest_avis_instruction_loanrequest_date_comite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='modalite_paiement',
            field=models.CharField(choices=[('journalier', 'Journalier'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel')], default='mensuel', help_text='Cadence de remboursement (Article 8) — choix définitif sauf demande écrite.', max_length=16),
        ),
        migrations.AddField(
            model_name='loanrenewal',
            name='interets_au_comptant',
            field=models.BooleanField(default=False, help_text='Si True, les intérêts sont versés cash à la reconduction (taux 10 %). Sinon ils sont reportés avec le capital (taux 15 %). Article 11.'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='modalite_paiement',
            field=models.CharField(choices=[('journalier', 'Journalier'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel')], default='mensuel', help_text='Cadence de remboursement choisie par le membre (Article 8).', max_length=16),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duree_mois',
            field=models.PositiveIntegerField(help_text='Durée en mois, dérivée du montant via les paliers du règlement (Article 7).'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='taux_interet',
            field=models.DecimalField(decimal_places=4, help_text='Taux flat appliqué une seule fois sur le montant (Règlement, Article 5). Par défaut 0.1000 (= 10 % par transaction).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanrenewal',
            name='nouvelle_duree_mois',
            field=models.PositiveIntegerField(default=1, help_text='Durée additionnelle (Règlement, Article 10) — fixée à 1 mois par défaut. Conservée modifiable pour rétro-compat.'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='duree_mois',
            field=models.PositiveIntegerField(help_text='Déduit automatiquement du montant via le tableau de paliers du règlement.'),
        ),
    ]
