# Generated by Django 5.2.14 on 2026-05-19 16:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_modalite_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninstallment',
            name='montant_penalite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='penalite_appliquee_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
