# Generated by Django 5.2.14 on 2026-05-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loaninstallment_montant_penalite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='mise_en_demeure_at',
            field=models.DateTimeField(blank=True, help_text='Date de la dernière mise en demeure envoyée (Article 13).', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='mise_en_demeure_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Nombre de mises en demeure émises pour ce crédit.'),
        ),
    ]
