# Generated by Django 5.2.14 on 2026-05-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_loan_mise_en_demeure_at_loan_mise_en_demeure_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="issu_reconduction",
            field=models.BooleanField(
                default=False,
                help_text="True si ce crédit est né d'une reconduction — non reconductible à nouveau.",
            ),
        ),
    ]
