# Generated by Django 5.2.14 on 2026-05-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0007_loan_issu_reconduction"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanDurationTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("montant_min", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "montant_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "duree_mois",
                    models.PositiveSmallIntegerField(
                        help_text="Nombre de mois de remboursement pour ce palier."
                    ),
                ),
                ("actif", models.BooleanField(db_index=True, default=True)),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Ordre d'évaluation (plus bas = plus tôt). Utile uniquement si plusieurs paliers se chevauchent — sinon laisser 100.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Palier de durée (Art. 7)",
                "verbose_name_plural": "Paliers de durée (Art. 7)",
                "ordering": ["ordering", "montant_min"],
            },
        ),
        migrations.CreateModel(
            name="PaymentModalityConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=16, unique=True)),
                ("libelle", models.CharField(max_length=64)),
                (
                    "installments_per_month",
                    models.PositiveSmallIntegerField(
                        help_text="Nombre d'échéances par mois pour cette cadence (ex. 30 pour journalier, 4 pour hebdo, 1 pour mensuel)."
                    ),
                ),
                ("actif", models.BooleanField(db_index=True, default=True)),
                ("ordering", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "verbose_name": "Modalité de paiement (Art. 8)",
                "verbose_name_plural": "Modalités de paiement (Art. 8)",
                "ordering": ["ordering", "code"],
            },
        ),
    ]
