# Generated by Django 5.2.14 on 2026-05-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0008_loandurationtier_paymentmodalityconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="taux_penalite",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Taux de pénalité (Article 12) figé au décaissement. Par défaut 0.5000 (= 50 %). NULL = crédit antérieur à EXT-versioning.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="taux_interet",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Taux flat appliqué une seule fois sur le montant (Règlement, Article 5). Par défaut 0.1000 (= 10 % par transaction). FIGÉ au décaissement — un changement de taux global n'affecte que les futurs crédits.",
                max_digits=5,
            ),
        ),
    ]
