# Generated by Django 5.2.14 on 2026-05-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0010_backfill_taux_penalite"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="contentieux_declenche_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de bascule en CONTENTIEUX (déclenche la saisie épargne).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="epargne_saisie_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date du prélèvement forcé sur l'épargne du membre.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="epargne_saisie_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant effectivement prélevé sur l'épargne (≤ solde_restant).",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="penalite_globale_appliquee_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date d'application de la pénalité globale 50 % × solde_restant.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="penalite_globale_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant de la pénalité globale ajoutée au solde restant.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="poursuite_judiciaire_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date d'engagement des poursuites (épargne insuffisante).",
                null=True,
            ),
        ),
    ]
