# Generated by Django 5.2.14 on 2026-05-31 05:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0011_loan_contentieux_declenche_at_loan_epargne_saisie_at_and_more"),
        ("members", "0008_brc_and_seniority"),
    ]

    operations = [
        migrations.CreateModel(
            name="LenderAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "montant_alloue",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant en XAF financé par ce prêteur.",
                        max_digits=14,
                    ),
                ),
                (
                    "quote_part",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Ratio (0.00000001 — 1.0) figé au funding ; détermine la fraction des intérêts à reverser au prêteur (LOT 9). Toujours égal à ``montant_alloue / Loan.montant`` mais stocké pour éviter les arrondis successifs.",
                        max_digits=10,
                    ),
                ),
                (
                    "interest_share_paid_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cumul des intérêts déjà versés à ce prêteur sur ce crédit.",
                        max_digits=14,
                    ),
                ),
                (
                    "lender",
                    models.ForeignKey(
                        help_text="Le membre prêteur qui finance cette quote-part du crédit.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lender_allocations",
                        to="members.member",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lender_allocations",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allocation prêteur",
                "verbose_name_plural": "Allocations prêteur",
                "ordering": ["loan", "-created_at"],
            },
        ),
    ]
