# Generated by Django 5.2.14 on 2026-05-31 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0012_lenderallocation"),
        ("savings", "0007_lenderconsent_lendertranche"),
    ]

    operations = [
        migrations.AddField(
            model_name="lenderallocation",
            name="tranche",
            field=models.ForeignKey(
                blank=True,
                help_text="Tranche explicite consommée (mode B). Null si le funding utilise directement le solde global du prêteur (mode A).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="savings.lendertranche",
            ),
        ),
        migrations.AddIndex(
            model_name="lenderallocation",
            index=models.Index(
                fields=["loan", "lender"], name="loans_lende_loan_id_969663_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lenderallocation",
            index=models.Index(
                fields=["lender", "-created_at"], name="loans_lende_lender__4d33bb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lenderallocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tranche__isnull", False)),
                fields=("loan", "tranche"),
                name="lender_allocation_unique_tranche_per_loan",
            ),
        ),
    ]
