# Generated by Django 5.2.14 on 2026-05-31 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0013_lenderallocation_tranche_and_more"),
        ("members", "0008_brc_and_seniority"),
        ("savings", "0007_lenderconsent_lendertranche"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanFundingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant à financer (= Loan.montant, copié pour traçabilité).",
                        max_digits=14,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de réponse (fenêtre 24h)"),
                            ("all_accepted", "Tous accepté (ou silence tacite)"),
                            ("reallocating", "Réallocation en cours (un refus)"),
                            ("en_attente_funding", "En attente — funding impossible"),
                            ("funded", "Financé (allocations posées)"),
                            ("cancelled", "Annulé (intervention admin)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            (
                                "first_fit",
                                "First-fit (prêteurs avec plus de capacité d'abord)",
                            ),
                            ("balanced", "Balanced (réparti équitablement)"),
                        ],
                        default="first_fit",
                        help_text="Algorithme d'allocation utilisé. Tunable globalement via AppSetting.",
                        max_length=12,
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Date butoir de la vague courante (= created_at + funding.window_hours). Réinitialisée à chaque réallocation.",
                    ),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de finalisation (passage à FUNDED ou EN_ATTENTE_FUNDING).",
                        null=True,
                    ),
                ),
                (
                    "wave_number",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Numéro de vague (incrementé à chaque réallocation). 1 = vague initiale.",
                    ),
                ),
                (
                    "loan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funding_request",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de financement crédit",
                "verbose_name_plural": "Demandes de financement crédit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LenderConsentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "montant_propose",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant proposé à ce prêteur pour cette vague.",
                        max_digits=14,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de réponse"),
                            ("accepted", "Acceptée (réponse explicite)"),
                            ("auto_accepted", "Acceptée tacitement (24h écoulées)"),
                            ("refused", "Refusée"),
                            ("obsolete", "Obsolète (remplacée par une vague suivante)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Date butoir individuelle (= created_at + funding.window_hours). Au-delà, le cron pose AUTO_ACCEPTED.",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de la réponse explicite (None pour AUTO_ACCEPTED).",
                        null=True,
                    ),
                ),
                (
                    "refus_motif",
                    models.TextField(
                        blank=True,
                        help_text="Motif facultatif fourni par le prêteur en cas de refus.",
                    ),
                ),
                (
                    "lender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_requests_received",
                        to="members.member",
                    ),
                ),
                (
                    "tranche",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tranche cible (mode B). Null en mode A : une tranche sera créée à la finalisation pour matérialiser l'engagement.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_requests",
                        to="savings.lendertranche",
                    ),
                ),
                (
                    "funding_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_requests",
                        to="loans.loanfundingrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de consentement prêteur",
                "verbose_name_plural": "Demandes de consentement prêteur",
                "ordering": ["funding_request", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="loanfundingrequest",
            index=models.Index(
                fields=["statut", "deadline"], name="loans_loanf_statut_a99963_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lenderconsentrequest",
            index=models.Index(
                fields=["lender", "statut"], name="loans_lende_lender__8352c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lenderconsentrequest",
            index=models.Index(
                fields=["statut", "deadline"], name="loans_lende_statut_2295ec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lenderconsentrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("statut", "obsolete"), _negated=True),
                fields=("funding_request", "lender"),
                name="lender_consent_request_unique_active",
            ),
        ),
    ]
