# Generated by Django 5.2.14 on 2026-05-31 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0014_loanfundingrequest_lenderconsentrequest_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lenderconsentrequest",
            name="lender_consent_request_unique_active",
        ),
    ]
