# Generated by Django 5.2.14 on 2026-06-01 18:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "loans",
            "0015_remove_lenderconsentrequest_lender_consent_request_unique_active",
        ),
        ("payments", "0004_payment_nb_jours_couverts"),
    ]

    operations = [
        migrations.AddField(
            model_name="loaninstallment",
            name="interets_payes",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.CreateModel(
            name="LenderInterestPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Part d'intérêts versée au prêteur sur cette imputation (XAF).",
                        max_digits=14,
                    ),
                ),
                ("date", models.DateTimeField(db_index=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interest_payouts",
                        to="loans.lenderallocation",
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        help_text="Échéance dont la part intérêt a généré ce versement.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lender_interest_payouts",
                        to="loans.loaninstallment",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        help_text="Paiement remboursement à l'origine de l'imputation qui a généré ce versement intérêt prêteur.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lender_interest_payouts",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versement intérêt prêteur",
                "verbose_name_plural": "Versements intérêt prêteur",
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["allocation", "-date"],
                        name="loans_lende_allocat_4ec01f_idx",
                    ),
                    models.Index(
                        fields=["installment", "-date"],
                        name="loans_lende_install_ee017c_idx",
                    ),
                ],
            },
        ),
    ]
