# Generated by Django 5.2.14 on 2026-06-01 18:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0016_loaninstallment_interets_payes_lenderinterestpayout"),
        ("members", "0008_brc_and_seniority"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrequest",
            name="avaliste",
            field=models.ForeignKey(
                blank=True,
                help_text="Ancien qui se porte garant. Posé après ``AvalisteConsent.statut = ACCEPTED``. NULL pour les voies SENIOR_BRC et CAMPAIGN.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan_requests_avalisee",
                to="members.member",
            ),
        ),
        migrations.AlterField(
            model_name="loanrequest",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente (frais à payer)"),
                    ("en_instruction", "En instruction"),
                    ("en_attente_acceptation_membre", "Contre-proposition à accepter"),
                    ("approuvee", "Approuvée"),
                    ("rejetee", "Rejetée"),
                    (
                        "en_attente_avaliste",
                        "En attente de l'acceptation de l'avaliste",
                    ),
                    ("rejetee_avaliste", "Refusée par l'avaliste (terminal)"),
                ],
                db_index=True,
                default="en_attente",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AvalisteConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de réponse"),
                            ("accepted", "Acceptée"),
                            ("refused", "Refusée"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "epargne_borrower_at_request",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cumul épargne (collecte + classique) du demandeur au moment de la demande.",
                        max_digits=14,
                    ),
                ),
                (
                    "epargne_avaliste_at_request",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cumul épargne (collecte + classique) de l'avaliste au moment de la demande.",
                        max_digits=14,
                    ),
                ),
                (
                    "couverture_ratio",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Ratio (épargne_borrower + épargne_avaliste) / montant_demande calculé au moment de la demande. Doit être ≥ ``loans.avaliste.min_coverage_ratio`` (défaut 1.0000).",
                        max_digits=6,
                    ),
                ),
                (
                    "identification_numero_saisi",
                    models.CharField(
                        help_text="Numéro identification AVALISTE tapé par le demandeur (brut).",
                        max_length=32,
                    ),
                ),
                (
                    "identification_nom_saisi",
                    models.CharField(
                        help_text="Nom de famille AVALISTE tapé par le demandeur (brut, casse d'origine).",
                        max_length=200,
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de réponse explicite (accept/refuse).",
                        null=True,
                    ),
                ),
                (
                    "refus_motif",
                    models.TextField(
                        blank=True, help_text="Motif facultatif si refus."
                    ),
                ),
                (
                    "avaliste",
                    models.ForeignKey(
                        help_text="Membre ancien désigné. Résolu via numero_membre + nom au moment de la création du consentement.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avaliste_consents",
                        to="members.member",
                    ),
                ),
                (
                    "loan_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliste_consent",
                        to="loans.loanrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consentement avaliste",
                "verbose_name_plural": "Consentements avaliste",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["avaliste", "statut"],
                        name="loans_avali_avalist_9f92e4_idx",
                    ),
                    models.Index(
                        fields=["statut", "-created_at"],
                        name="loans_avali_statut_1ec576_idx",
                    ),
                ],
            },
        ),
    ]
