# Generated by Django 5.2.14 on 2026-06-02 03:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0017_loanrequest_avaliste_alter_loanrequest_statut_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanrequest",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente (frais à payer)"),
                    ("en_instruction", "En instruction"),
                    ("en_attente_acceptation_membre", "Contre-proposition à accepter"),
                    ("approuvee", "Approuvée"),
                    ("rejetee", "Rejetée"),
                    (
                        "en_attente_avaliste",
                        "En attente de l'acceptation de l'avaliste",
                    ),
                    ("rejetee_avaliste", "Refusée par l'avaliste (terminal)"),
                    (
                        "en_validation_campagne",
                        "Micro-crédit campagne — en validation activité",
                    ),
                    ("rejetee_campagne", "Refusée — micro-crédit campagne (terminal)"),
                ],
                db_index=True,
                default="en_attente",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="MicrocreditCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nom",
                    models.CharField(
                        help_text='Libellé interne, ex. "Campagne commerçants Q3 2026".',
                        max_length=120,
                    ),
                ),
                (
                    "profil_cible",
                    models.CharField(
                        help_text='Profil ciblé (libre), ex. "commercants", "parents", "agriculteurs".',
                        max_length=64,
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        db_index=True,
                        help_text="Premier jour d'ouverture de la campagne (inclus).",
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(
                        db_index=True,
                        help_text="Dernier jour d'ouverture (inclus). Au-delà, le cron pose actif=False.",
                    ),
                ),
                (
                    "montant_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Plancher de montant (FCFA). 0 = pas de plancher.",
                        max_digits=14,
                    ),
                ),
                (
                    "montant_max",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Plafond de montant (FCFA), ex. 50 000.",
                        max_digits=14,
                    ),
                ),
                (
                    "taux_interet",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Taux flat appliqué à la création du Loan, ex. 0.10 (10 %).",
                        max_digits=5,
                    ),
                ),
                (
                    "nb_jours_recouvrement",
                    models.PositiveIntegerField(
                        help_text="Durée du recouvrement par collectes journalières dédiées, ex. 60."
                    ),
                ),
                (
                    "plafond_beneficiaires",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre maximum de bénéficiaires acceptés (None = pas de plafond). Bloque les nouvelles demandes une fois atteint.",
                        null=True,
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Toggle admin. La campagne n'accepte des demandes QUE si actif=True ET aujourd'hui ∈ [date_debut, date_fin]. Posé False par le cron ``close_expired_campaigns`` après date_fin.",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date à laquelle la campagne a été clôturée (cron ou admin).",
                        null=True,
                    ),
                ),
                (
                    "close_reason",
                    models.CharField(
                        blank=True,
                        help_text='Motif de clôture, ex. "expired", "manual", "quota_reached".',
                        max_length=64,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin auteur de la campagne (audit).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="microcampaigns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne micro-crédit",
                "verbose_name_plural": "Campagnes micro-crédit",
                "ordering": ["-date_debut", "-id"],
            },
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="microcampaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Campagne micro-crédit d'origine. NULL pour les voies SENIOR_BRC et AVALISTE. Posé à la soumission via ``submit_microcampaign_request``.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan_requests",
                to="loans.microcreditcampaign",
            ),
        ),
        migrations.AddIndex(
            model_name="microcreditcampaign",
            index=models.Index(
                fields=["actif", "-date_debut"], name="loans_micro_actif_2ed064_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="microcreditcampaign",
            index=models.Index(
                fields=["actif", "date_fin"], name="loans_micro_actif_95c846_idx"
            ),
        ),
    ]
