# Generated by Django 5.2.14 on 2026-06-02 04:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0018_alter_loanrequest_statut_microcreditcampaign_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JudicialEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_instance", "En instance (D — instruction huissier)"),
                            (
                                "decision_rendue",
                                "Décision rendue (E — saisie biens autorisée)",
                            ),
                            (
                                "executee",
                                "Exécutée (E — biens saisis, recouvrement enregistré)",
                            ),
                            (
                                "classee_sans_suite",
                                "Classée sans suite (irrécouvrable)",
                            ),
                        ],
                        db_index=True,
                        default="en_instance",
                        max_length=24,
                    ),
                ),
                (
                    "declenche_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "declenche_mode",
                    models.CharField(
                        default="manual",
                        help_text='Mode de déclenchement: "manual", "auto", "hybrid".',
                        max_length=16,
                    ),
                ),
                (
                    "motif",
                    models.TextField(
                        help_text="Raison d'ouverture (rédaction admin / template auto)."
                    ),
                ),
                (
                    "documents_attaches",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste libre de références à des Documents (cf. members.Document).",
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(
                        blank=True,
                        help_text="Date de la décision judiciaire ; posée à DECISION_RENDUE.",
                        null=True,
                    ),
                ),
                (
                    "biens_saisissables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Inventaire libre des biens autorisés à la saisie. Liste d'objets ex. [{'description': 'Mobylette', 'valeur_estimee': '120000'}].",
                    ),
                ),
                (
                    "execution_date",
                    models.DateField(
                        blank=True,
                        help_text="Date d'exécution de la saisie (posée à EXECUTEE).",
                        null=True,
                    ),
                ),
                (
                    "montant_recouvre",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Montant effectivement recouvré après vente / cession des biens saisis. Décrémente ``Loan.solde_restant`` à l'exécution.",
                        max_digits=14,
                    ),
                ),
                (
                    "biens_saisis",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Inventaire effectif des biens saisis lors de l'exécution. Peut différer de ``biens_saisissables`` (subset, ou ajouts).",
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "close_reason",
                    models.CharField(
                        blank=True,
                        help_text='ex. "executee", "irrecouvrable".',
                        max_length=64,
                    ),
                ),
                (
                    "declenche_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin auteur (NULL si mode 'auto' déclenché par le cron).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="judicial_escalations_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.OneToOneField(
                        help_text="Crédit objet de la procédure (1 escalade max par crédit).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="judicial_escalation",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalade judiciaire",
                "verbose_name_plural": "Escalades judiciaires",
                "ordering": ["-declenche_at"],
                "indexes": [
                    models.Index(
                        fields=["statut", "-declenche_at"],
                        name="loans_judic_statut_95bfca_idx",
                    ),
                    models.Index(
                        fields=["declenche_mode", "statut"],
                        name="loans_judic_declenc_224a49_idx",
                    ),
                ],
            },
        ),
    ]
