# Generated by Django 5.2.14 on 2026-06-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_judicialescalation'),
        ('members', '0009_member_microcampaign_alter_member_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcreditcampaign',
            name='flyer',
            field=models.ImageField(blank=True, help_text='Visuel attaché à la campagne (PNG/JPG) — affiché aux membres ciblés.', null=True, upload_to='coop/microcampaigns/flyers/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='microcreditcampaign',
            name='targeted_members',
            field=models.ManyToManyField(blank=True, help_text='Membres explicitement ciblés (notification + segmentation manuelle admin).', related_name='targeted_campaigns', to='members.member'),
        ),
    ]
