# Generated by Django 5.2.14 on 2026-06-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0020_microcreditcampaign_flyer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrenewal",
            name="extra_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Champs FormSchema additionnels (id_champ → valeur).",
            ),
        ),
        migrations.AddField(
            model_name="loanrenewal",
            name="form_schema_version",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Version du FormSchema 'loan_renewal' actif lors de la soumission.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="extra_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Champs FormSchema additionnels (id_champ → valeur).",
            ),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="form_schema_version",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Version du FormSchema 'loan_request' actif lors de la soumission.",
                null=True,
            ),
        ),
    ]
