# Generated by Django 5.2.14 on 2026-06-10 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0021_ch4_form_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrequest",
            name="field_visit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent qui a effectué la visite terrain.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_requests_visited",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="field_visit_done_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date à laquelle la visite terrain a été effectuée.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="field_visit_note",
            field=models.TextField(
                blank=True,
                help_text="Compte-rendu de la visite (observations sur le demandeur, l'activité, le local).",
            ),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="field_visit_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("favorable", "Favorable — peut être approuvée définitivement"),
                    ("defavorable", "Défavorable — propose le rejet"),
                    ("a_revoir", "À revoir — informations à compléter"),
                ],
                help_text="Recommandation de l'agent terrain au comité.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="loanrequest",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente (frais à payer)"),
                    ("en_instruction", "En instruction"),
                    ("en_attente_acceptation_membre", "Contre-proposition à accepter"),
                    (
                        "approuvee_provisoire",
                        "Approuvée provisoirement (visite terrain à effectuer)",
                    ),
                    ("approuvee", "Approuvée"),
                    ("rejetee", "Rejetée"),
                    (
                        "en_attente_avaliste",
                        "En attente de l'acceptation de l'avaliste",
                    ),
                    ("rejetee_avaliste", "Refusée par l'avaliste (terminal)"),
                    (
                        "en_validation_campagne",
                        "Micro-crédit campagne — en validation activité",
                    ),
                    ("rejetee_campagne", "Refusée — micro-crédit campagne (terminal)"),
                ],
                db_index=True,
                default="en_attente",
                max_length=32,
            ),
        ),
    ]
