# Generated by Django 5.2.14 on 2026-07-02 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0027_microcampaign_soft_delete"),
        ("members", "0014_password_setup_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="microcreditcampaign",
            name="frais_etude_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Frais d'étude de dossier pour cette campagne (FCFA). NULL = tarif DEMANDE_CREDIT standard (legacy). 0 = gratuit.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="microcreditcampaign",
            name="membre_requis",
            field=models.BooleanField(
                default=True,
                help_text="True = seul un membre existant peut postuler (flux membre). False = un VISITEUR non-membre peut candidater via la vitrine ; à l'acceptation, un compte est créé sans frais d'adhésion (13K).",
            ),
        ),
        migrations.AlterField(
            model_name="lenderinterestpayout",
            name="installment",
            field=models.ForeignKey(
                blank=True,
                help_text="Échéance dont la part intérêt a généré ce versement. NULL en mode CH-11 source — le versement a lieu à T0 (décaissement) et n'est rattaché à aucune échéance individuelle.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lender_interest_payouts",
                to="loans.loaninstallment",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interets_retenus_source",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Intérêts ponctionnés par la coop à la mise à disposition. En mode 'source' = montant × taux_interet. En mode 'echeances' = 0. NULL = legacy pre-CH-11.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CampaignApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=120)),
                ("prenom", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=32)),
                (
                    "email",
                    models.EmailField(
                        help_text="Requis : sert à envoyer le lien de définition du mot de passe.",
                        max_length=254,
                    ),
                ),
                (
                    "montant_demande",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("motif", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("acceptee", "Acceptée"),
                            ("rejetee", "Rejetée"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=12,
                    ),
                ),
                ("motif_rejet", models.CharField(blank=True, max_length=2000)),
                ("date_decision", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="loans.microcreditcampaign",
                    ),
                ),
                (
                    "decide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_applications_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_application",
                        to="loans.loanrequest",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_applications",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "statut"],
                        name="loans_campa_campaig_4ea941_idx",
                    )
                ],
            },
        ),
    ]
