# Generated by Django 5.2.14 on 2026-07-02 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0028_microcreditcampaign_frais_etude_montant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="microcreditcampaign",
            name="documents_requis",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste de libellés de pièces exigées du candidat (ex. « Preuve d'activité commerçant »). Le visiteur uploade un fichier par libellé en postulant.",
            ),
        ),
        migrations.CreateModel(
            name="CampaignApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Libellé de la pièce exigée.", max_length=200
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        help_text="Fichier uploadé par le candidat (image ou PDF).",
                        upload_to="coop/microcampaigns/candidatures/%Y/%m/",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="loans.campaignapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce candidature campagne",
                "verbose_name_plural": "Pièces candidatures campagne",
                "ordering": ["id"],
            },
        ),
    ]
