# Generated by Django 5.2.14 on 2026-07-08 06:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0029_microcreditcampaign_documents_requis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="avalisteconsent",
            name="montant_caution",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Montant réellement engagé/gelé par l'avaliste (le manque = montant − épargne dispo du demandeur).",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="montant_gele_demandeur",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Épargne classique propre du demandeur gelée en garantie de ce crédit (bloquée au retrait jusqu'à clôture).",
                max_digits=14,
            ),
        ),
    ]
