# Generated by Django 5.2.14 on 2026-07-08 07:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0030_avalisteconsent_montant_caution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrequest",
            name="garantie_description",
            field=models.TextField(
                blank=True,
                help_text="Description du bien proposé en garantie (saisie par le demandeur).",
            ),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="garantie_materielle",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Cette demande s'appuie sur une garantie matérielle (bien) au lieu d'un avaliste.",
            ),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="garantie_valeur_estimee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Valeur estimée du bien par la commission (éval manuelle admin). Doit être ≥ montant demandé pour approuver.",
                max_digits=14,
            ),
        ),
    ]
