# Generated by Django 5.2.14 on 2026-07-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0031_loanrequest_garantie_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="avalisteconsent",
            name="cni_avaliste",
            field=models.CharField(
                blank=True,
                help_text="Numéro de CNI de l'avaliste, saisi par lui à l'acceptation.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="avalisteconsent",
            name="cni_avaliste_fichier",
            field=models.FileField(
                blank=True,
                help_text="Scan/photo de la CNI de l'avaliste, uploadé à l'acceptation.",
                null=True,
                upload_to="coop/avaliste/cni/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="cni_demandeur",
            field=models.CharField(
                blank=True,
                help_text="Numéro de CNI du demandeur, saisi à la soumission de la demande.",
                max_length=32,
            ),
        ),
    ]
