# Generated by Django 5.2.14 on 2026-07-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0032_avalisteconsent_cni_avaliste_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrequest",
            name="date_limite_etude",
            field=models.DateField(
                blank=True,
                help_text="Échéance indicative d'étude par la commission (soumission + délai max).",
                null=True,
            ),
        ),
    ]
