# Generated by Django 5.2.14 on 2026-07-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0033_loanrequest_date_limite_etude"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrequest",
            name="avaliste_nom_saisi",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="avaliste_numero_saisi",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="frais_demande_credit_paye",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Frais d'étude encaissés (agence, mobile money ou déduction épargne). Porte d'entrée de l'instruction.",
            ),
        ),
    ]
