# Generated by Django 5.2.14 on 2026-07-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0034_loanrequest_avaliste_nom_saisi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="en_attente_decaissement",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True = crédit approuvé mais argent pas encore versé. Exclut le crédit des pénalités et de la saisie tant qu'il n'est pas décaissé.",
            ),
        ),
    ]
