# Generated by Django 5.2.14 on 2026-07-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0036_backfill_campaign_carnets"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="masque_par_membre",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True = crédit clôturé masqué de la vue du membre. Aucune suppression en base ; l'admin le voit toujours.",
            ),
        ),
    ]
