# Generated by Django 5.2.14 on 2026-07-19 18:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0037_loan_masque_par_membre"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrenewal",
            name="capital_restant_snapshot",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Capital restant dû au moment de la demande (base du calcul).",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="loanrenewal",
            name="interets_dus",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Intérêts à verser au comptant. 0 si intérêts reportés.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="loanrenewal",
            name="interets_payes_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date d'encaissement des intérêts au comptant.",
                null=True,
            ),
        ),
    ]
