# Generated by Django 5.2.14 on 2026-07-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0039_repair_avaliste_fees_stuck"),
    ]

    operations = [
        migrations.AddField(
            model_name="lenderallocation",
            name="restitue_par_apport",
            field=models.BooleanField(
                default=False,
                help_text="True si ce prêteur a été restitué par un apport coop anticipé.",
            ),
        ),
    ]
