# Generated by Django 5.2.14 on 2026-07-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0040_lenderallocation_restitue_par_apport"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrequest",
            name="motif_gel_demandeur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Motif lisible du gel du collatéral demandeur.",
                max_length=180,
            ),
        ),
    ]
