# Generated by Django 5.2.15 on 2026-07-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0041_apport_personnel_motif_gel'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='montant_decouvert',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Part prêtée sur confiance (montant − gagé) = exposition de la coop.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='montant_gage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Part du crédit adossée à une garantie (apport gelé + caution + bien/campagne).', max_digits=14, null=True),
        ),
    ]
