# Generated by Django 5.2.15 on 2026-07-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0042_loan_montant_decouvert_loan_montant_gage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='privilege_accorde',
            field=models.BooleanField(default=False, help_text='Le comité a accordé un découvert sur privilège (ancien apprenant, confiance…).'),
        ),
        migrations.AddField(
            model_name='loan',
            name='privilege_motif',
            field=models.TextField(blank=True, default='', help_text='Justification du privilège accordé (éléments retenus par le comité).'),
        ),
    ]
