# Generated by Django 5.2.14 on 2026-08-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0043_loan_privilege_accorde_loan_privilege_motif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanrequest",
            name="moyen_reception",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tara_om", "Orange Money"),
                    ("tara_momo", "MTN MoMo"),
                    ("agence_especes", "Espèces en agence"),
                ],
                help_text="Canal choisi par le membre pour recevoir le décaissement. Pilote l'auto-fill du payout Tara à la mise à disposition.",
                max_length=16,
            ),
        ),
    ]
