# Generated by Django 5.2.14 on 2026-08-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0044_alter_loanrequest_moyen_reception"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrequest",
            name="is_brc",
            field=models.BooleanField(
                default=False,
                help_text="True si le demandeur déclare avoir fréquenté le centre de formation BRC. Attribut informatif couplable à toute voie ; jugé par le comité à l'évaluation.",
            ),
        ),
    ]
