# Generated by Django 5.2.14 on 2026-08-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0045_loanrequest_is_brc"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignapplication",
            name="extra_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Réponses aux champs personnalisés du formulaire de campagne (FormSchema loan_request) : {field_id: valeur}.",
            ),
        ),
        migrations.AddField(
            model_name="campaignapplication",
            name="form_schema_version",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Version du FormSchema loan_request utilisée à la candidature.",
                null=True,
            ),
        ),
    ]
