# Generated by Django 5.2.14 on 2026-05-15 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('objet', models.CharField(max_length=200)),
                ('corps_html', models.TextField()),
                ('corps_texte', models.TextField(blank=True, help_text='Fallback for clients that block HTML.')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Declared variables (list of strings) for editor validation.')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Template d'email",
                'verbose_name_plural': "Templates d'emails",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinataire', models.EmailField(max_length=254)),
                ('objet', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('echec', 'Échec')], db_index=True, default='en_attente', max_length=12)),
                ('erreur', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='members.member')),
                ('template', models.ForeignKey(db_column='template_code', on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='coop_notifications.emailtemplate', to_field='code')),
            ],
            options={
                'verbose_name': 'Email envoyé',
                'verbose_name_plural': 'Emails envoyés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(help_text="Free-form key, e.g. 'payment.confirmed'.", max_length=64)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, help_text='Optional internal link to the related resource.', max_length=255)),
                ('lue', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'lue', '-created_at'], name='coop_notifi_user_id_030490_idx')],
            },
        ),
    ]
