# Generated by Django 5.2.14 on 2026-05-25 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop_notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Requis (toujours actif)"),
                            ("OPTIONAL", "Optionnel (activable)"),
                            ("BLOCKED", "Bloqué (kill-switch)"),
                        ],
                        db_index=True,
                        default="OPTIONAL",
                        max_length=10,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Effectif uniquement quand status=OPTIONAL.",
                    ),
                ),
                (
                    "sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Si vrai, l'admin doit confirmer avant de couper (événement à impact légal ou opérationnel fort).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration d'événement",
                "verbose_name_plural": "Configurations d'événements",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EventHook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-mail (template)"),
                            ("AUDIT_ONLY", "Audit seulement (silencieux)"),
                        ],
                        default="EMAIL",
                        max_length=16,
                    ),
                ),
                (
                    "target_template_code",
                    models.CharField(
                        blank=True,
                        help_text="Code EmailTemplate à rendre. Si vide, on utilise event.code.",
                        max_length=64,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("ordering", models.PositiveSmallIntegerField(default=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hooks",
                        to="coop_notifications.eventconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hook d'événement",
                "verbose_name_plural": "Hooks d'événements",
                "ordering": ["event", "ordering"],
            },
        ),
    ]
