# Generated by Django 5.2.14 on 2026-05-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="nb_jours_couverts",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Multi-jours pré-payé pour la collecte (refonte 2026). Défaut 1 = paiement standard.",
            ),
        ),
    ]
