# Generated by Django 5.2.14 on 2026-06-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_nb_jours_couverts"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_placement",
            field=models.BooleanField(
                default=False,
                help_text="Sous-canal épargne classique : True = placement bloqué 12 mois (intérêt mensuel), False = libre (retrait à tout moment).",
            ),
        ),
    ]
