# Generated by Django 5.2.14 on 2026-07-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_ch3_placement_sous_canal"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="frais_transaction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="rateparam",
            name="code",
            field=models.CharField(
                choices=[
                    ("LOAN_INTEREST", "Taux d'intérêt crédit (par transaction)"),
                    ("SAVINGS_INTEREST_MONTHLY", "Taux d'intérêt épargne (mensuel)"),
                    ("RENEWAL_CASH", "Reconduction — intérêts au comptant"),
                    ("RENEWAL_DEFERRED", "Reconduction — intérêts reportés"),
                    ("LATE_PENALTY", "Pénalité de non-versement"),
                    ("TRANSACTION_FEE", "Frais de transaction sur versement (%)"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
