# Generated by Django 5.2.14 on 2026-07-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_payment_frais_transaction_alter_rateparam_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="source",
            field=models.CharField(
                choices=[
                    ("manuel", "Saisie agence"),
                    ("mobile_money", "Mobile Money"),
                    ("deduction_epargne", "Déduction sur épargne classique"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
