# Generated by Django 5.2.14 on 2026-08-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_alter_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feetype",
            name="code",
            field=models.CharField(
                choices=[
                    ("INSCRIPTION", "Frais d'inscription"),
                    ("ADHESION", "Frais d'adhésion"),
                    ("DEMANDE_CREDIT", "Frais de demande de crédit"),
                    ("RECONDUCTION", "Frais de reconduction"),
                    ("CARNET", "Frais de carnet (collecte / épargne)"),
                    ("CARNET_TONTINE", "Frais de carnet tontine"),
                    ("CARNET_CAISSE", "Frais de carnet caisse scolaire"),
                ],
                max_length=24,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[
                    ("epargne", "Épargne"),
                    ("epargne_classique", "Épargne classique"),
                    ("caisse_scolaire", "Caisse scolaire"),
                    ("tontine_alimentaire", "Tontine alimentaire"),
                    ("frais_inscription", "Frais d'inscription"),
                    ("frais_adhesion", "Frais d'adhésion"),
                    ("frais_demande_credit", "Frais de demande de crédit"),
                    ("frais_reconduction", "Frais de reconduction"),
                    ("frais_carnet", "Frais de carnet"),
                    ("frais_carnet_tontine", "Frais de carnet tontine"),
                    ("frais_carnet_caisse", "Frais de carnet caisse scolaire"),
                    ("remboursement", "Remboursement"),
                    ("decaissement", "Décaissement"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
