# Generated by Django 5.2.14 on 2026-08-27 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_alter_feetype_code_alter_payment_type"),
        (
            "special_collections",
            "0003_remove_specialcollectioncycle_uniq_open_cycle_per_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="special_cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="special_collections.specialcollectioncycle",
            ),
        ),
    ]
