# Generated by Django 5.2.14 on 2026-08-27 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_payment_special_cycle"),
        (
            "special_collections",
            "0005_grouptontine_grouptontineloan_grouptontinemember_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="group_tontine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="special_collections.grouptontine",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[
                    ("epargne", "Épargne"),
                    ("epargne_classique", "Épargne classique"),
                    ("caisse_scolaire", "Caisse scolaire"),
                    ("tontine_alimentaire", "Tontine alimentaire"),
                    ("tontine_groupe", "Cotisation tontine de groupe"),
                    ("frais_inscription", "Frais d'inscription"),
                    ("frais_adhesion", "Frais d'adhésion"),
                    ("frais_demande_credit", "Frais de demande de crédit"),
                    ("frais_reconduction", "Frais de reconduction"),
                    ("frais_carnet", "Frais de carnet"),
                    ("frais_carnet_tontine", "Frais de carnet tontine"),
                    ("frais_carnet_caisse", "Frais de carnet caisse scolaire"),
                    ("remboursement", "Remboursement"),
                    ("decaissement", "Décaissement"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
