# Generated by Django 5.2.14 on 2026-08-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_payment_group_tontine_alter_payment_type"),
        ("special_collections", "0006_grouptontinetransaction_acted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="group_loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="special_collections.grouptontineloan",
            ),
        ),
    ]
