# Generated by Django 5.2.17 on 2026-08-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payment_group_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('epargne', 'Épargne'), ('epargne_classique', 'Épargne classique'), ('caisse_scolaire', 'Caisse scolaire'), ('tontine_alimentaire', 'Tontine'), ('tontine_groupe', 'Cotisation tontine de groupe'), ('frais_inscription', "Frais d'inscription"), ('frais_adhesion', "Frais d'adhésion"), ('frais_demande_credit', 'Frais de demande de crédit'), ('frais_reconduction', 'Frais de reconduction'), ('frais_carnet', 'Frais de carnet'), ('frais_carnet_tontine', 'Frais de carnet tontine'), ('frais_carnet_caisse', 'Frais de carnet caisse scolaire'), ('remboursement', 'Remboursement'), ('decaissement', 'Décaissement')], db_index=True, max_length=24),
        ),
    ]
