# Generated by Django 5.2.14 on 2026-10-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_alter_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="placement_force_admin",
            field=models.BooleanField(
                default=False,
                help_text="Placement autorisé par un admin hors des fenêtres normales (date-limite globale ou ancienneté du membre). Sans effet si is_placement est faux.",
            ),
        ),
    ]
