# Generated by Django 5.2.14 on 2026-05-15 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_membre', models.CharField(db_index=True, max_length=24, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('radie', 'Radié')], db_index=True, default='actif', max_length=12)),
                ('date_adhesion', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_adhesion'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_doc', models.CharField(choices=[('piece_identite', "Pièce d'identité"), ('justificatif_revenu', 'Justificatif de revenu'), ('contrat_credit', 'Contrat de crédit'), ('acte_garantie', 'Acte de garantie'), ('autre', 'Autre')], max_length=24)),
                ('entite_liee_type', models.CharField(blank=True, help_text='Member|Loan|LoanRequest|MembershipRequest', max_length=32)),
                ('entite_liee_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to='coop/documents/%Y/%m/')),
                ('nom_original', models.CharField(blank=True, max_length=255)),
                ('taille', models.PositiveIntegerField(default=0)),
                ('member', models.ForeignKey(blank=True, help_text='Owning member; nullable when attached to a pre-member request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('motivation', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], db_index=True, default='en_attente', max_length=12)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('instruit_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_requests_instructed', to=settings.AUTH_USER_MODEL)),
                ('member', models.OneToOneField(blank=True, help_text='Set once the request is approved and a Member is created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adhesion_request', to='members.member')),
            ],
            options={
                'verbose_name': "Demande d'adhésion",
                'verbose_name_plural': "Demandes d'adhésion",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['statut', '-date_adhesion'], name='members_mem_statut_4be828_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['entite_liee_type', 'entite_liee_id'], name='members_doc_entite__4300a5_idx'),
        ),
    ]
