# Generated by Django 5.2.14 on 2026-05-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='city',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Private notes for staff — never shown to the applicant.'),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='language',
            field=models.CharField(default='fr', max_length=8),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='user_agent',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='motivation',
            field=models.TextField(blank=True, help_text="Free-form 'Pourquoi rejoindre ?' field from the public form."),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='prenom',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
