# Generated by Django 5.2.14 on 2026-05-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_membershiprequest_city_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookletOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('payee', 'Payée'), ('en_impression', 'En impression'), ('delivree', 'Délivrée')], db_index=True, default='payee', max_length=20)),
                ('date_impression', models.DateTimeField(blank=True, null=True)),
                ('date_delivrance', models.DateTimeField(blank=True, null=True)),
                ('notes_agence', models.TextField(blank=True, help_text="Notes internes (lieu d'impression, retrait…).")),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booklet_orders', to='members.member')),
                ('payment', models.OneToOneField(help_text='Le Payment frais_carnet ayant déclenché la commande.', on_delete=django.db.models.deletion.PROTECT, related_name='booklet_order', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Commande de carnet',
                'verbose_name_plural': 'Commandes de carnet',
                'ordering': ['-created_at'],
            },
        ),
    ]
