# Generated by Django 5.2.14 on 2026-05-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_bookletorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='quartier_localite',
            field=models.CharField(blank=True, help_text="Lieu précis d'habitation dans la ville (quartier, rue, repère).", max_length=200),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='statut_pro',
            field=models.CharField(blank=True, choices=[('salarie', 'Salarié'), ('commercant', 'Commerçant'), ('artisan', 'Artisan'), ('sans_emploi', 'Sans emploi'), ('autre', 'Autre')], default='', help_text='Statut social et professionnel (Article 2).', max_length=16),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='urgence_lien',
            field=models.CharField(blank=True, help_text="Lien avec le contact d'urgence (parent, conjoint, ami, …).", max_length=80),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='urgence_nom',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='urgence_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp — peut être identique au téléphone normal (Article 2).', max_length=32),
        ),
    ]
