# Generated by Django 5.2.14 on 2026-05-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_membershiprequest_quartier_localite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='date_entretien',
            field=models.DateTimeField(blank=True, help_text="Date de l'entretien avec le comité (Article 3).", null=True),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='entretien_avis',
            field=models.TextField(blank=True, help_text="Avis/recommandation du comité après l'entretien."),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='entretien_favorable',
            field=models.BooleanField(blank=True, help_text="True si l'entretien est favorable à l'admission.", null=True),
        ),
    ]
