# Generated by Django 5.2.14 on 2026-05-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_membershiprequest_date_entretien_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="date_derniere_reinscription",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date de référence pour le calcul de l'anniversaire annuel. Mise à jour à chaque re-souscription confirmée par l'admin.",
                null=True,
            ),
        ),
    ]
