# Generated by Django 5.2.14 on 2026-05-30 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_backfill_date_derniere_reinscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="brc_validated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de validation du statut BRC (par admin).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="brc_validated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin ayant validé le statut BRC du membre.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brc_validations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="is_brc_member",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True si le justificatif BRC a été validé par un admin.",
            ),
        ),
        migrations.CreateModel(
            name="BRCDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fichier", models.FileField(upload_to="coop/brc/%Y/%m/")),
                ("nom_original", models.CharField(blank=True, max_length=255)),
                (
                    "taille",
                    models.PositiveIntegerField(
                        default=0, help_text="Taille du fichier en octets."
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de validation"),
                            ("valide", "Validé"),
                            ("rejete", "Rejeté"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=12,
                    ),
                ),
                (
                    "motif_rejet",
                    models.TextField(
                        blank=True,
                        help_text="Motif fourni par l'admin en cas de rejet du justificatif.",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de la décision admin (validation ou rejet).",
                        null=True,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brc_documents",
                        to="members.member",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin ayant validé ou rejeté le document.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brc_documents_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Justificatif BRC",
                "verbose_name_plural": "Justificatifs BRC",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "statut"],
                        name="members_brc_member__4d0a1d_idx",
                    )
                ],
            },
        ),
    ]
