# Generated by Django 5.2.14 on 2026-06-02 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0018_alter_loanrequest_statut_microcreditcampaign_and_more"),
        ("members", "0008_brc_and_seniority"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="microcampaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Campagne d'origine pour un Member TEMPORAIRE (§8 BUSINESS_RULES_2026). NULL pour les adhérents standards.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="beneficiaires",
                to="loans.microcreditcampaign",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="statut",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("suspendu", "Suspendu"),
                    ("radie", "Radié"),
                    ("temporaire", "Temporaire (micro-crédit campagne)"),
                ],
                db_index=True,
                default="actif",
                max_length=12,
            ),
        ),
    ]
