# Generated by Django 5.2.14 on 2026-06-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_member_microcampaign_alter_member_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiprequest",
            name="extra_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Champs FormSchema additionnels (id_champ → valeur).",
            ),
        ),
        migrations.AddField(
            model_name="membershiprequest",
            name="form_schema_version",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Version du FormSchema 'adhesion' actif lors de la soumission.",
                null=True,
            ),
        ),
    ]
