# Generated by Django 5.2.14 on 2026-06-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_ch4_form_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="schema_field_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifiant du champ FormSchema source (ex. 'cga_attestation'). Vide pour les uploads historiques.",
                max_length=80,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["entite_liee_type", "entite_liee_id", "schema_field_id"],
                name="members_doc_entite__42333c_idx",
            ),
        ),
    ]
