# Generated by Django 5.2.15 on 2026-06-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_password_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='cni_recto',
            field=models.FileField(blank=True, help_text='CNI face recto (image ou PDF).', null=True, upload_to='coop/adhesion/cni/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='cni_verso',
            field=models.FileField(blank=True, help_text='CNI face verso (image ou PDF).', null=True, upload_to='coop/adhesion/cni/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='photo_identite',
            field=models.ImageField(blank=True, help_text='Selfie / photo portrait du demandeur.', null=True, upload_to='coop/adhesion/photo/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='plan_localisation',
            field=models.FileField(blank=True, help_text='Plan ou photo du domicile (image ou PDF).', null=True, upload_to='coop/adhesion/plan/%Y/%m/'),
        ),
    ]
