# Generated by Django 5.2.15 on 2026-06-27 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_adhesion_pieces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordSetupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(help_text='Token URL-safe (secrets.token_urlsafe(32)). Stocke en clair car a la fois confidentiel et a usage unique tres court.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Au-dela : token invalide meme si non utilise (72h par defaut).')),
                ('used_at', models.DateTimeField(blank=True, help_text='Posee a la consommation. Toute reutilisation est refusee.', null=True)),
                ('ip_request', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_confirm', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_setup_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'used_at'], name='members_pas_user_id_2eddd9_idx'), models.Index(fields=['expires_at'], name='members_pas_expires_3ae3ba_idx')],
            },
        ),
    ]
