# Generated by Django 5.2.14 on 2026-07-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_password_setup_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookletorder",
            name="annee",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Année de la commande (plusieurs carnets/an autorisés).",
                null=True,
            ),
        ),
    ]
