# Generated by Django 5.2.14 on 2026-07-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0016_staffrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="brcdocument",
            name="champ_source",
            field=models.CharField(
                blank=True,
                help_text="Id du champ FormSchema source (ex. cga_brc_preuve).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="brcdocument",
            name="loan_request_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Demande de crédit d'où provient le justificatif, si applicable.",
                null=True,
            ),
        ),
    ]
