# Generated by Django 5.2.14 on 2026-07-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0018_backfill_brc_from_loan_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="photo_profil",
            field=models.ImageField(
                blank=True,
                help_text="Avatar de profil choisi par le membre (modifiable).",
                null=True,
                upload_to="coop/profil/%Y/%m/",
            ),
        ),
    ]
