# Generated by Django 5.2.15 on 2026-07-27 15:50

from django.db import migrations, models
from django.db.models import F


def backfill_date_activation(apps, schema_editor):
    """Marque comme « déjà activé » les membres qui l'ont manifestement été,
    pour ne pas mal router leur future réactivation (garde du hook adhésion).

    Preuves d'activation antérieure : statut ACTIF, OU une date de réinscription
    posée (le renouvellement n'existe que pour un membre déjà activé). On prend
    ``date_derniere_reinscription`` sinon ``date_adhesion`` comme date de repli.
    Un SUSPENDU sans réinscription reste NULL (traité comme primo).
    """
    Member = apps.get_model("members", "Member")
    qs = Member.objects.filter(date_activation__isnull=True).filter(
        models.Q(statut="actif") | models.Q(date_derniere_reinscription__isnull=False)
    )
    qs.filter(date_derniere_reinscription__isnull=False).update(
        date_activation=F("date_derniere_reinscription")
    )
    Member.objects.filter(date_activation__isnull=True, statut="actif").update(
        date_activation=F("date_adhesion")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_member_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_activation',
            field=models.DateField(blank=True, help_text='Date de la 1re activation. NULL = jamais activé (primo-adhérent).', null=True),
        ),
        migrations.RunPython(backfill_date_activation, migrations.RunPython.noop),
    ]
