# Generated by Django 5.2.14 on 2026-08-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0020_member_date_activation"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="pieces_a_fournir",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True si le membre (créé par l'admin) doit encore charger ses pièces.",
            ),
        ),
    ]
