# Generated by Django 5.2.14 on 2026-08-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0021_member_pieces_a_fournir"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookletorder",
            name="type",
            field=models.CharField(
                choices=[
                    ("collecte", "Épargne / collecte journalière"),
                    ("tontine", "Tontine alimentaire"),
                    ("caisse_scolaire", "Caisse scolaire"),
                ],
                db_index=True,
                default="collecte",
                help_text="Type de carnet (un carnet distinct par type).",
                max_length=20,
            ),
        ),
    ]
